////////////////////////////////////////////////////////
/////   TASKS | 
/////   S3 -> CORE_DWH 
/////   CORE_DWH -> DATA_MART

CREATE OR REPLACE TASK Copy_S3_CORE_DWH_CET_Standard
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = 'USING CRON */2 * * * * Europe/Warsaw'
    TIMESTAMP_INPUT_FORMAT = 'YYYY-MM-DD HH24:MI:SS'
    AS
    CALL STG_CORE_DWH();


CREATE OR REPLACE TASK Copy_CORE_DWH_DATA_MART
    WAREHOUSE = COMPUTE_WH
    TIMESTAMP_INPUT_FORMAT = 'YYYY-MM-DD HH24:MI:SS'
    //AFTER Copy_S3_CORE_DWH_CET_Standard
    AS
    CALL DATA_MART.CORE_DWH_DATA_MART();
    
 
ALTER TASK Copy_S3_CORE_DWH_CET_Standard RESUME; //SUSPEND RESUME
ALTER TASK Copy_CORE_DWH_DATA_MART RESUME;
