CREATE OR REPLACE STREAM
  dim_nation_stream
  ON TABLE DATA_MART.DIM_NATION;

CREATE OR REPLACE STREAM
  dim_customer_stream
  ON TABLE DATA_MART.DIM_CUSTOMER;

CREATE OR REPLACE STREAM
  fact_lineitem_stream
  ON TABLE DATA_MART.FACT_LINEITEM;

CREATE OR REPLACE STREAM
  fact_orders_stream
  ON TABLE DATA_MART.FACT_ORDERS;

CREATE OR REPLACE STREAM
  dim_part_stream
  ON TABLE DATA_MART.DIM_PART;

CREATE OR REPLACE STREAM
  dim_partsupp_stream
  ON TABLE DATA_MART.DIM_PARTSUPP;

CREATE OR REPLACE STREAM
  dim_region_stream
  ON TABLE DATA_MART.DIM_REGION;

CREATE OR REPLACE STREAM
  dim_supplier_stream
  ON TABLE DATA_MART.DIM_SUPPLIER;
